version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mp-backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mp-frontend
    # No necesita .env, todo está “bakeado” en build. Si tu frontend
    # quisiera apuntar a backend por nombre de servicio, podrías usar:
    # environment:
    #   - REACT_APP_API_URL=http://backend:4000/api
    ports:
      - "3000:80"
    depends_on:
      - backend
